// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	ListConnectedUserIDs(ctx context.Context, userID string) ([]interface{}, error)
	PostToNewsFeed(ctx context.Context, arg PostToNewsFeedParams) error
}

var _ Querier = (*Queries)(nil)
